# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-29 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygas', '0002_auto_20190529_1803'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_info',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permission_info',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='permission_info',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group_info',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Permission_info',
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
