# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_auto_20190529_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=32, verbose_name='组别')),
            ],
            options={
                'verbose_name': '分组表',
                'verbose_name_plural': '分组表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=32, unique=True, verbose_name='一级菜单名称')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='一级菜单图标')),
                ('weight', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Permission_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('url', models.CharField(max_length=32, verbose_name='权限')),
                ('menu_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='二级菜单名称')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='二级菜单图标')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='一级菜单')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission_info')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('group', models.ManyToManyField(to='rbac.Group_info', verbose_name='用户所属组别')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='group_info',
            name='permission',
            field=models.ManyToManyField(to='rbac.Permission_info', verbose_name='组别拥有的权限'),
        ),
    ]
