# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygas', '0003_auto_20190529_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='gs_metertypeinfo',
            name='check_user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
