# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygas', '0004_gs_metertypeinfo_check_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gs_metertypeinfo',
            name='allo_user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
