# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygas', '0005_gs_metertypeinfo_allo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_result',
            name='MeterEvery',
            field=models.CharField(default='00000000000000000000000000000000', max_length=32),
        ),
        migrations.AddField(
            model_name='meter_result',
            name='MeterPrivilege',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='meter_result_record',
            name='MeterEvery',
            field=models.CharField(default='00000000000000000000000000000000', max_length=32),
        ),
        migrations.AddField(
            model_name='meter_result_record',
            name='MeterPrivilege',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='meter_test',
            name='MeterEvery',
            field=models.CharField(default='00000000000000000000000000000000', max_length=32),
        ),
        migrations.AddField(
            model_name='meter_test',
            name='MeterPrivilege',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
