# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygas', '0007_gs_metertypeinfo_meterprivilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_result',
            name='CheckTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meter_result',
            name='ManufactureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mygas.Manufacture'),
        ),
        migrations.AddField(
            model_name='meter_result',
            name='Subtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meter_result_record',
            name='CheckTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meter_result_record',
            name='ManufactureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mygas.Manufacture'),
        ),
        migrations.AddField(
            model_name='meter_result_record',
            name='Subtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meter_test',
            name='CheckTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meter_test',
            name='ManufactureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mygas.Manufacture'),
        ),
        migrations.AddField(
            model_name='meter_test',
            name='Subtime',
            field=models.DateTimeField(null=True),
        ),
    ]
